/**
 * 1 - Make a copy of this file.
 * 2 - Rename copy : instance.config.ts
 * 3 - Fill in the blanks
 *
 * @todo Consider setting up a dedicated test instance that a CI job could run
 *       these tests against.
 */
export const config = {
  BASE_URL: "http://localhost:3114",
  ACCESS_TOKEN: "pNQnUCoZ.Zd6OCJZtYHf6ynN+5RSu0FihC/71MhtOXwy8H+Ejtz0=",
  LINKEDIN_RECONNECT_BASIC_ACCOUNT_ID: "",
  LINKEDIN_RECONNECT_BASIC_USERNAME: "",
  LINKEDIN_RECONNECT_BASIC_PASSWORD: "",
  LINKEDIN_RECONNECT_COOKIE_ACCOUNT_ID: "",
  LINKEDIN_RECONNECT_COOKIE_ACCESS_TOKEN: "",
  LINKEDIN_RECONNECT_COOKIE_USER_AGENT: "",
  LINKEDIN_CHECKPOINT_ACCOUNT_ID: "",
  LINKEDIN_CHECKPOINT_CODE: "",
  LINKEDIN_USERNAME: "",
  LINKEDIN_ACCESS_TOKEN: "",
  LINKEDIN_PASSWORD: "",
  LINKEDIN_USER_AGENT: "",
  INSTAGRAM_USERNAME: "",
  INSTAGRAM_PASSWORD: "",
  INSTAGRAM_RECONNECT_ACCOUNT_ID: "",
  INSTAGRAM_RECONNECT_USERNAME: "",
  INSTAGRAM_RECONNECT_PASSWORD: "",
  TWITTER_USERNAME: "",
  TWITTER_PASSWORD: "",
  TWITTER_RECONNECT_ACCOUNT_ID: "",
  TWITTER_RECONNECT_USERNAME: "",
  TWITTER_RECONNECT_PASSWORD: "",
  MESSENGER_USERNAME: "",
  MESSENGER_PASSWORD: "",
  MESSENGER_RECONNECT_ACCOUNT_ID: "",
  MESSENGER_RECONNECT_USERNAME: "",
  MESSENGER_RECONNECT_PASSWORD: "",
  WHATSAPP_RECONNECT_ACCOUNT_ID: "",
  TELEGRAM_RECONNECT_ACCOUNT_ID: "",
  MAIL_USERNAME: "",
  MAIL_PASSWORD: "",
  MAIL_IMAP_PORT: 993,
  MAIL_IMAP_HOST: "ssl0.ovh.net",
  MAIL_SMTP_PORT: 465,
  MAIL_SMTP_HOST: "ssl0.ovh.net",
  MAIL_IMAP_ENCRYPTION: "default",
  logRequestPayload: false,
  logRequestResult: false,
};
